# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clan_msg.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'clan_msg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63lan_msg.proto\"\x8b\x04\n\x08\x63lan_msg\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x1f\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x11.clan_msg.Nested2\x1a\xcf\x03\n\x07Nested2\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\x04\x12\x11\n\tchat_type\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12)\n\x06\x66ield9\x18\t \x01(\x0b\x32\x19.clan_msg.Nested2.Nested9\x12\x10\n\x08language\x18\n \x01(\t\x12+\n\x07\x66ield13\x18\r \x01(\x0b\x32\x1a.clan_msg.Nested2.Nested13\x12/\n\x0b\x65mpty_field\x18\x0e \x01(\x0b\x32\x1a.clan_msg.Nested2.Nested14\x1a\n\n\x08Nested14\x1a\x8a\x01\n\x07Nested9\x12\x13\n\x0bPlayer_Name\x18\x01 \x01(\t\x12\x11\n\tavatar_id\x18\x02 \x01(\x03\x12\x11\n\tbanner_id\x18\x03 \x01(\x03\x12\x0c\n\x04rank\x18\x04 \x01(\x05\x12\x11\n\tClan_Name\x18\x08 \x01(\t\x12\x0f\n\x07\x66ield10\x18\n \x01(\x05\x12\x12\n\nrank_point\x18\x0b \x01(\x05\x1a?\n\x08Nested13\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08url_type\x18\x02 \x01(\x05\x12\x14\n\x0curl_platform\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clan_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLAN_MSG']._serialized_start=19
  _globals['_CLAN_MSG']._serialized_end=542
  _globals['_CLAN_MSG_NESTED2']._serialized_start=79
  _globals['_CLAN_MSG_NESTED2']._serialized_end=542
  _globals['_CLAN_MSG_NESTED2_NESTED14']._serialized_start=326
  _globals['_CLAN_MSG_NESTED2_NESTED14']._serialized_end=336
  _globals['_CLAN_MSG_NESTED2_NESTED9']._serialized_start=339
  _globals['_CLAN_MSG_NESTED2_NESTED9']._serialized_end=477
  _globals['_CLAN_MSG_NESTED2_NESTED13']._serialized_start=479
  _globals['_CLAN_MSG_NESTED2_NESTED13']._serialized_end=542
# @@protoc_insertion_point(module_scope)