# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Clan_Startup.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'Clan_Startup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43lan_Startup.proto\"\x8a\x01\n\nClanPacket\x12\x10\n\x08\x43lan_Pos\x18\x01 \x01(\x05\x12 \n\x04\x44\x61ta\x18\x02 \x01(\x0b\x32\x12.ClanPacket.Nested\x1aH\n\x06Nested\x12\x0f\n\x07\x43lan_ID\x18\x01 \x01(\x03\x12\x11\n\tClan_Type\x18\x02 \x01(\x05\x12\x1a\n\x12\x43lan_Compiled_Data\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Clan_Startup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLANPACKET']._serialized_start=23
  _globals['_CLANPACKET']._serialized_end=161
  _globals['_CLANPACKET_NESTED']._serialized_start=89
  _globals['_CLANPACKET_NESTED']._serialized_end=161
# @@protoc_insertion_point(module_scope)